server:
  port: 80
spring:
  application:
    name: default-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
  zipkin:
    base-url: http://localhost:9411/