spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marchocode/spring-cloud-config-repo
      discovery:
        enabled: true
  application:
    name: config-server
server:
  port: 8888
